### ISSUE TITLE
How to use OT matrix to interpolate between two categorical distribution? 

### ISSUE THREAD

**Issue by 2019mohamed** [facebookresearch/meta-ot#6]
In the paper, we can use OT mapping to interpolate between images and so on..., so how to use it in categorical distribution such as sequences

**Comment by bamos** [comment]
For categorical distributions, one challenge is that you need to define a metric/distance over the atoms of much it costs to move one to another, e.g., how different one token is from another. Once you have the costs, then you should be able to do a similar interpolation to the discrete OT interpolations we have in here, where we take the distances to be the Euclidean or spherical distances between the pixel or spherical locations.

![image](https://user-images.githubusercontent.com/707462/188037355-b4721b5b-07af-4051-af87-dac1d315e132.png)
