### ISSUE TITLE
Using meta-ot for mathcing distributions of different dimensions 

### ISSUE THREAD

**Issue by ttsesm** [facebookresearch/meta-ot#7]
Hi @bamos ,

I am quite curious whether meta-ot could work for my following problem and I would be interested to hear your opinion or any other suggestion that you might have based on your experience with the optimization methods.

Briefly to explain you my task, I am trying to compute the distance between gaussian distributions of different dimensions (in my case 2D and 3D) and find their coupling (matchings or the best correspondences between the two sets). Taking into account that, I considered using the Gromov-Wasserstein dinstace based on cost matrices computed on the Bures manifold (which didn't work that perfectly).

In a more practical way, imagine that you have the following test case where I have a set of 3D gaussian distributions defined as ellipsoids by their mean value μ (being a 1x3 vector) and their corresponding covariance matrices Σ1 (being a 3x3 matrix). Then I have a set of 2D gaussian distributions defined as ellipses again by their mean value ν (being a 1x2 vector) and their corresponding covariance matrices Σ2 (being a 2x2 matrix). So in practice the ellipses are the projected ellipsoids in a plane through a linear map P, ![image](https://github.com/facebookresearch/meta-ot/assets/10189018/2a412b1e-ce71-4834-8093-755d9ab41aca).

![Picture11](https://github.com/dp4846/eigmom_shape_stats/assets/10189018/ca793c99-b0a9-4f71-b08a-257f9b801500)

So, in simple words I want to find which ellipsoid corresponds to which ellipse by using their covariance information. In the ideal case scenario, the coupling is one-to-one, however in our real case scenario we will have outliers. Meaning that not all ellipsoids will match with all ellipses and that's why we think that an unbalanced GW or a solution like [rGW](https://www1.se.cuhk.edu.hk/~manchoso/papers/outlier_gw-neurips23.pdf) could be useful for our study, however without success so far.

Considering though that the two distributions are not in the same space we need somehow to bring them into the same space where we can apply the matching and find the coupling and the transport plan. For this purpose we thought that a suitable approach would be to first compute the cost matrices of each set in the Bures Wasserstein manifold (this should create something similar to a weighted graph of all distributions with all distributions in the same set) and then compute their correspondence (or their distance on the different sets) with the Gromov-Wasserstein distance.

We tried to play a bit with an oracle test ablation study of 50 ellipsoids with 50 ellipses where there is always a one-to-one correspondence, meaning the first 2D gaussian corresponds to the first 3D gaussian, the second with the second, the third with the third and so on. So at the end the coupling should be an identity matrix. However as you can see from the output bellow I am not really getting the desired output:

![image](https://github.com/facebookresearch/meta-ot/assets/10189018/15323854-25de-4e09-b307-fe8d66cd4040)

My data are in the following format (example of 10 matching gaussians in the two sets):
**2D gaussians:**
```
Covariances
ct = np.array([[[0.00049392, 0.00018833],
        [0.00018833, 0.00007765]],
       [[0.00037171, 0.00021303],
        [0.00021303, 0.00012497]],
       [[0.00004997, 0.00002954],
        [0.00002954, 0.00012977]],
       [[0.00005111, 0.00000863],
        [0.00000863, 0.00002055]],
       [[0.00022878, 0.00014253],
        [0.00014253, 0.00023158]],
       [[0.00010538, 0.00007804],
        [0.00007804, 0.00030141]],
       [[0.00001159, 0.00000829],
        [0.00000829, 0.00000615]],
       [[0.00007754, 0.00002211],
        [0.00002211, 0.00011025]],
       [[0.00070302, 0.00060664],
        [0.00060664, 0.00052477]],
       [[0.00109267, 0.00122162],
        [0.00122162, 0.00137384]]], dtype=np.float32)

Means
mt = np.array([[-0.34575066, -0.05927338],
       [-0.16067392, -0.15656751],
       [ 0.0884882 ,  0.7348885 ],
       [-0.09218572,  0.05595953],
       [ 0.21521865,  0.38351792],
       [-0.22240582,  0.30064186],
       [-0.0520223 , -0.18196055],
       [-0.4030493 ,  0.22060394],
       [-0.17406262, -0.09412329],
       [ 0.3939966 ,  0.21849754]], dtype=np.float32)
```
**3D gaussians:**
```
Covariances
Cs = np.array([[[ 0.00055704,  0.0002181 ,  0.00020697],
        [ 0.0002181 ,  0.00026268,  0.00017932],
        [ 0.00020697,  0.00017932,  0.00013152]],

       [[ 0.00029736,  0.00036497, -0.00025849],
        [ 0.00036497,  0.0005222 , -0.00034746],
        [-0.00025849, -0.00034746,  0.00028704]],

       [[ 0.00013889, -0.00002427,  0.00009434],
        [-0.00002427,  0.000106  , -0.00010998],
        [ 0.00009434, -0.00010998,  0.00020017]],

       [[ 0.00013997,  0.0000322 , -0.00003177],
        [ 0.0000322 ,  0.00013866,  0.0000159 ],
        [-0.00003177,  0.0000159 ,  0.00008226]],

       [[ 0.00015876,  0.00015987,  0.00013226],
        [ 0.00015987,  0.00046588, -0.0000928 ],
        [ 0.00013226, -0.0000928 ,  0.00045325]],

       [[ 0.00014214, -0.00009106,  0.00025811],
        [-0.00009106,  0.00042213,  0.00002785],
        [ 0.00025811,  0.00002785,  0.00058036]],

       [[ 0.00003409, -0.00000352,  0.00000672],
        [-0.00000352,  0.00000058, -0.00000025],
        [ 0.00000672, -0.00000025,  0.00000226]],

       [[ 0.00025886, -0.00007174, -0.00000447],
        [-0.00007174,  0.00020796,  0.00000071],
        [-0.00000447,  0.00000071,  0.00017473]],

       [[ 0.00000316, -0.00008337, -0.00002749],
        [-0.00008337,  0.00292826,  0.00008949],
        [-0.00002749,  0.00008949,  0.00106939]],

       [[ 0.00080745, -0.00143929, -0.00031194],
        [-0.00143929,  0.00750104,  0.00179461],
        [-0.00031194,  0.00179461,  0.0016364 ]]], dtype=np.float32)

Means
Ms = np.array([[ 0.17411666,  0.5035763 ,  0.42941484],
       [ 0.5251834 , -0.27657598, -0.18892948],
       [-0.5073861 ,  0.46957424, -0.90752286],
       [ 0.56422734, -0.4835634 , -0.91173404],
       [-0.5370846 ,  0.22988465, -0.2466668 ],
       [ 0.04097709,  0.48167574, -0.23595962],
       [ 0.49995327, -0.5364788 , -0.3129182 ],
       [ 0.4078352 ,  0.46962914, -0.3338474 ],
       [ 0.5331596 , -0.24272342, -0.30946448],
       [-0.57427835, -0.20426048, -0.28931147]], dtype=np.float32)
```

My question, considering your work and your experience with optimization methods and OT, is whether I can optimize somehow the matching output so that I can get more reliable correspondences between the ellipsoids and the ellipses of my two sets. Do you think meta-ot could be useful somehow?

Thanks.

**Comment by bamos** [comment]
Hi! I don't immediately see how Meta OT can fit into that setup as Meta OT is more about predicting solutions to OT problems when solving multiple ones at the same time. Separate from Meta OT here, it does seem like GW with the Bures-Wasserstein distance as the ground cost should give better couplings in your last example

**Comment by ttsesm** [comment]
I see, thanks for the feedback and your time ;-)
